export default [
    {   
        id:1,
        img: "deadpool.png",
        title: "Deadpool",
        date: "February 12",
        rating: 7.5,
        type: "Action",
        timeLen: "1h 48m",
        hitRate: 52,
    },
    {   
        id:2,
        img: "avatar.png",
        title: "Avatar",
        date: "December 16",
        rating: 8.0,
        type: "Sci-fi",
        timeLen: "3h 12m",
        hitRate: 103,
    },
    {   
        id:3,
        img: "babylon.png",
        title: "Babylon",
        date: "December 23",
        rating: 5.0,
        type: "Drama",
        timeLen: "3h 9m",
        hitRate: 10,
    },
    {   
        id:4,
        img: "knivesout.png",
        title: "Knives Out",
        date: "November 27",
        rating: 7.0,
        type: "Crime",
        timeLen: "2h 10m", 
        hitRate: 27,
    }
]